server:
  port: 8080
zk: 127.0.0.1:2181

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:h2:./dbdata/mydataharbor
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths:
        - src/main/*
      exclude: static/**,public/**


